# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true
  # media_dirs:
  #   streamgl: config/medias/streamgl

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.streamgl: debug
    custom_components.webrtc: debug

streamgl:
  gallery: config/medias
